/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-10-05 00:36:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findPwd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>:: 비트대학교 ::</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("input[type=\"number\"]::-webkit-outer-spin-button,\r\n");
      out.write("input[type=\"number\"]::-webkit-inner-spin-button {\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tpadding : 0;\r\n");
      out.write("\tbackground-image: url('./image/bg.png');\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left : 30%; \r\n");
      out.write("\tmargin-top : 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#find_pwd_image{\r\n");
      out.write("\tborder:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#find_pwd_box {\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("\twidth : 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#id_box {\r\n");
      out.write("\tdisplay: inline-block; \r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\twidth:220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#id_icon {\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#id{\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth : 150px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#submit_button {\r\n");
      out.write("\tmargin-left: 11px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tpadding-top :30px;\r\n");
      out.write("\tpadding-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#email_box {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\twidth : 220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#email_icon {\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#email {\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth : 150px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#submit {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 82px;\r\n");
      out.write("\tbackground-color: #083b90; \r\n");
      out.write("\tborder: none; \r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#boxes { \r\n");
      out.write("\twidth : 775px;\r\n");
      out.write("\theight : 478px; \r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop : 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box1{\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth : 375px;\r\n");
      out.write("\theight : 272px;\r\n");
      out.write("\tmargin-right: -6px;\r\n");
      out.write("\tborder: 1px solid #FFFFFF;\r\n");
      out.write("\tbackground-color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box2 {\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tbackground-color: #f3f6fc;\r\n");
      out.write("\twidth : 408px; \r\n");
      out.write("\theight : 274px; \r\n");
      out.write("\tleft : 48%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".go_box {\r\n");
      out.write("\twidth: 220px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tbackground-color:#f3f6fc;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcolor: #083b90;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tmargin-left: 90px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#under_menu {\r\n");
      out.write("\ttext-align: center; \r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".under_menu{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id = \"main\">\r\n");
      out.write("\t\t<div id=\"contents\">\r\n");
      out.write("\t\t\t<div id = \"title\">\r\n");
      out.write("\t\t\t\t<a href=\"login.do\">\r\n");
      out.write("\t\t\t\t\t<img src = \"image/logo2.png\">\r\n");
      out.write("\t\t\t\t</a> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div id = \"boxes\">\r\n");
      out.write("\t\t\t\t<div id =\"box1\">\r\n");
      out.write("\t\t\t\t\t<img src = \"image/findPwdPage.png\" id =\"find_pwd_image\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"box2\">\r\n");
      out.write("\t\t\t\t\t<form action=\"findPwdOk.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"findPwd\" id=\"find_pwd_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"findPwd\" id = \"id_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"image/idIcon.png\" id = \"id_icon\">&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"id\" placeholder=\"아이디\" required=\"required\" id =\"id\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"findPwd\" id = \"email_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"image/emailIcon.png\" id = \"email_icon\">&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" placeholder=\"이메일\" required=\"required\" id = \"email\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"findPwd\" id=\"submit_button\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"비밀번호 찾기\" id=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div id = \"under_menu\">\r\n");
      out.write("\t\t\t\t\t\t<a href =\"login.do\" id = \"login_page\" class =\"under_menu\">로그인 페이지</a>&nbsp;&nbsp;|&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"findId.do\" id = \"find_id\" class =\"under_menu\">아이디 찾기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
