/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-10-05 00:35:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>:: 비트대학교 ::</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("input[type=\"number\"]::-webkit-outer-spin-button,\r\n");
      out.write("input[type=\"number\"]::-webkit-inner-spin-button {\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tpadding : 0;\r\n");
      out.write("\tbackground-image: url('./image/bg.png');\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left : 30%; \r\n");
      out.write("\tmargin-top : 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#welcome_image{\r\n");
      out.write("\tborder:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login_box {\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("\twidth : 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#id_box {\r\n");
      out.write("\tdisplay: inline-block; \r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\twidth:220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#id_icon {\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#id{\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth : 150px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login_button {\r\n");
      out.write("\tmargin-left: 11px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tpadding-top :30px;\r\n");
      out.write("\tpadding-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pwd_box {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\twidth : 220px;\r\n");
      out.write("\theight : 41px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pwd_icon {\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pwd {\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth : 150px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 82px;\r\n");
      out.write("\tbackground-color: #083b90; \r\n");
      out.write("\tborder: none; \r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#remember_id {\r\n");
      out.write("\tfont-size: 13px; \r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#error {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor :#42bfee;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#finder {\r\n");
      out.write("\ttext-align: center; \r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tmargin-top:2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".find{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice_box{\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\ttext-align: left; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#boxes { \r\n");
      out.write("\twidth : 775px;\r\n");
      out.write("\theight : 478px; \r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop : 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box1{\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth : 375px;\r\n");
      out.write("\theight : 272px;\r\n");
      out.write("\tmargin-right: -6px;\r\n");
      out.write("\tborder: 1px solid #FFFFFF;\r\n");
      out.write("\tbackground-color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box2 {\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tbackground-color: #f3f6fc;\r\n");
      out.write("\twidth : 408px; \r\n");
      out.write("\theight : 274px; \r\n");
      out.write("\tleft : 48%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box3 {\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\ttop : 61%;\r\n");
      out.write("\twidth: 352px;\r\n");
      out.write("\theight: 200px; \r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\tpadding-left: 25px;\r\n");
      out.write("\tpadding-bottom: 25px;\r\n");
      out.write("\tpadding-top: 25px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-right : -6px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box4 {\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\ttop : 61%;\r\n");
      out.write("\tleft : 48%;\r\n");
      out.write("\twidth: 383px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\tpadding-left: 25px;\r\n");
      out.write("\tpadding-bottom: 25px;\r\n");
      out.write("\tpadding-top: 25px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #083b90;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tbackground-color:#E1E1E1;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tborder-color: #999999;\r\n");
      out.write("\tmargin-top: 12px;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id = \"main\">\r\n");
      out.write("\t\t<div id=\"contents\">\r\n");
      out.write("\t\t\t<div id = \"title\">\r\n");
      out.write("\t\t\t\t<a href=\"login.do\">\r\n");
      out.write("\t\t\t\t\t<img src = \"image/logo2.png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div id = \"boxes\">\r\n");
      out.write("\t\t\t\t<div id =\"box1\">\r\n");
      out.write("\t\t\t\t\t<img src = \"image/welcome.png\" id =\"welcome_image\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"box2\">\r\n");
      out.write("\t\t\t\t\t<form action=\"loginOk.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login\" id=\"login_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class = \"login\" id = \"id_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"image/idIcon.png\" id = \"id_icon\">&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"id\" placeholder=\"아이디\" required=\"required\" id =\"id\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${re_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class = \"login\" id = \"pwd_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"image/pwdIcon.png\" id = \"pwd_icon\">&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"pwd\" placeholder=\"비밀번호\" required=\"required\" id = \"pwd\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login\" id=\"login_button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"로그인\" class=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div id = \"remember_id\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type =\"checkbox\" name =\"cb_id\" value = \"checked\" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t아이디 저장 \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div id = \"finder\">\r\n");
      out.write("\t\t\t\t\t\t<a href =\"findId.do\" id = \"find_id\" class = \"find\">학번 찾기</a>&nbsp;&nbsp;|&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"findPwd.do\" id = \"find_pwd\" class = \"find\">비밀번호 찾기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div id = \"error\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_error }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div id = \"box3\">\r\n");
      out.write("\t\t\t\t\t<div id =\"notice_box\">\r\n");
      out.write("\t\t\t\t\t\t<div id = \"notice\">\r\n");
      out.write("\t\t\t\t\t\t\t공지사항\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id = \"notice_list\" >\r\n");
      out.write("\t\t\t\t\t\t\t<ul type = \"square\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><p><a href = \"board.do?BOARD_NO=1\">공지사항 1</a></p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><p><a href = \"board.do?BOARD_NO=2\">공지사항 2</a></p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><p><a href = \"board.do?BOARD_NO=3\">공지사항 3</a></p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><p><a href = \"board.do?BOARD_NO=4\">공지사항 4</a></p></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id = \"box4\">\r\n");
      out.write("\t\t\t\t\t<div id =\"menus\">\r\n");
      out.write("\t\t\t\t\t\t<div id = \"menu1\" class = \"menu\" onclick=\"location.href='http://naver.com'\">\r\n");
      out.write("\t\t\t\t\t\t\t네이버\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id = \"menu2\" class = \"menu\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("\t\t\t\t\t\t\t구글\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id = \"menu3\" class = \"menu\" onclick=\"location.href='http://naver.com'\">\r\n");
      out.write("\t\t\t\t\t\t\t드롭박스\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id = \"menu4\" class = \"menu\" onclick=\"location.href='https://www.dropbox.com/sh/y60we2a4h1bowdw/AADWxhikrixTFdDM9IYzqpoja?dl=0'\">\r\n");
      out.write("\t\t\t\t\t\t\t구글독스\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id = \"menu5\" class = \"menu\" onclick=\"location.href='http://discord.com'\">\r\n");
      out.write("\t\t\t\t\t\t\t디스코드\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id = \"menu6\" class = \"menu\" onclick=\"location.href='http://youtube.com'\">\r\n");
      out.write("\t\t\t\t\t\t\t유튜브\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /login.jsp(250,63) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${re_id != null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("checked=\"checked\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
