/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-10-05 07:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#main {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar{\r\n");
      out.write("\twidth : 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navs{\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".boxes{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".navs:hover{\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav1:hover + #wrap1{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav2:hover + #wrap2{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav3:hover + #wrap3{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap:hover{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<h2>hi</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("</header>\r\n");
      out.write("<nav>\r\n");
      out.write("<div id = \"main\">\r\n");
      out.write("\t<div class= \"navbar\">\r\n");
      out.write("\t\t<div id = \"box1\" class = \"boxes\">\r\n");
      out.write("\t\t\t<div class = \"navs\" id = \"nav1\">\r\n");
      out.write("\t\t\t메뉴1\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"wrap\" id = \"wrap1\">\r\n");
      out.write("\t\t\t\t<div class = \"nws\" id = \"nw1\">\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목1</div>\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목2</div>\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목3</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id = \"box2\" class = \"boxes\">\r\n");
      out.write("\t\t\t<div class = \"navs\" id = \"nav2\">\r\n");
      out.write("\t\t\t메뉴2\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"wrap\" id = \"wrap2\">\r\n");
      out.write("\t\t\t\t<div class = \"nws\" id = \"nw2\">\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목1</div>\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목2</div>\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목3</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id = \"box3\" class = \"boxes\">\r\n");
      out.write("\t\t\t<div class = \"navs\" id = \"nav3\">\r\n");
      out.write("\t\t\t메뉴3\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"wrap\" id = \"wrap3\">\r\n");
      out.write("\t\t\t\t<div class = \"nws\" id = \"nw3\">\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목1</div>\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목2</div>\r\n");
      out.write("\t\t\t\t\t<div class = \"list\">항목3</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
