/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-10-05 03:07:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class change_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tvertical-align : middle;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable{\r\n");
      out.write("\t\ttext-align: middle; \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\th2{\r\n");
      out.write("\t\tcolor: #083b90;\r\n");
      out.write("\t\tmargin-left: 90px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#form-control { \r\n");
      out.write("\t\theight: 20px; \r\n");
      out.write("\t\twidth: 120px;\r\n");
      out.write("\t\tline-height: normal;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv{\r\n");
      out.write("\t\tpadding:10px;\t\r\n");
      out.write("\t}\r\n");
      out.write("\tlabel{\r\n");
      out.write("\t\tpadding-top : 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tab_menu_container{\r\n");
      out.write("\t\tmargin-left: 70px;\r\n");
      out.write("\t\tmargin-right: 80px;\r\n");
      out.write("\t\twidth : 700px;\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tpadding-top : 0;\r\n");
      out.write("\t\tpadding-bottom: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.tab_menu_btn {\r\n");
      out.write("\t  width:80px;\r\n");
      out.write("\t  height:40px;\r\n");
      out.write("\t  background-color : #f1f4f8;\r\n");
      out.write("\t  transition:0.3s all;\r\n");
      out.write("\t  border : 1px solid gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tab_menu_btn.on {\r\n");
      out.write("\t  border-top:2px solid #083b90;\r\n");
      out.write("\t  border-left : 1px solid gray;\r\n");
      out.write("\t  font-weight:700;\r\n");
      out.write("\t  color:#083b90;\r\n");
      out.write("\t  background-color: #ffffff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tab_menu_btn:hover {\r\n");
      out.write("\t  color:#f1f4f8;\r\n");
      out.write("\t}\r\n");
      out.write("\t.table2{\r\n");
      out.write("\t\tmargin-left: 80px;\r\n");
      out.write("\t\tmargin-right: 80px;\r\n");
      out.write("\t\tbackground-color: #f1f4f8;\r\n");
      out.write("\t\twidth : 800px;\r\n");
      out.write("\t}\r\n");
      out.write("\tth {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    td {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t.container1{\r\n");
      out.write("\t\tdisplay: table-cell;\r\n");
      out.write("\t\tpadding-bottom:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container2{\r\n");
      out.write("\t\tdisplay: table-cell;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container3{\r\n");
      out.write("\t\tdisplay: table-cell;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container4{\r\n");
      out.write("\t\tdisplay: table-cell;\r\n");
      out.write("\t}\r\n");
      out.write("\t#submit{\r\n");
      out.write("\t\tpadding-top: 10px;\r\n");
      out.write("\t\tmargin-left: 80px;\r\n");
      out.write("\t\tborder : 1px solid black;\r\n");
      out.write("\t\tbackground-color: #083b90;\r\n");
      out.write("\t\tcolor:#f1f4f8;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>학사정보</h2>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"adminStudentInfo\">\r\n");
      out.write("\t<div class=\"info\">\r\n");
      out.write("\t\t<div id=\"tabs\" class=\"tab_menu_container\">\r\n");
      out.write("\t\t\t<button class=\"tab_menu_btn\" type=\"button\" onclick=\"location='studentInfo.do'\">기본정보</button>\r\n");
      out.write("\t    \t<button class=\"tab_menu_btn\" type=\"button\" onclick=\"location='startEndDate.do'\">입학/졸업</button>\r\n");
      out.write("\t  \t\t<button class=\"tab_menu_btn on\" type=\"button\" onclick=\"location='change.do'\">학적변동</button>\r\n");
      out.write("\t  \t\t<button class=\"tab_menu_btn\" type=\"button\" onclick=\"location='listGrade.do'\">성적</button>\r\n");
      out.write("\t  \t\t<button class=\"tab_menu_btn\" type=\"button\" onclick=\"location='detailClass.jsp'\">수강</button>\r\n");
      out.write("\t  \t\t<button class=\"tab_menu_btn\" type=\"button\" onclick=\"location='listReg.do'\">등록</button>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t\t\t<table border=\"1\" class=\"table2\">\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<th>년도</th>\r\n");
      out.write("\t\t\t\t\t<th>학기</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"200px\">변동구분</th>\r\n");
      out.write("\t\t\t\t\t<th>변동학년</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"200px\">변동일자</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"div년도\" class=\"form-control\" name=\"change_year\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${change.change_year }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"div학기\" class=\"form-control\" name=\"change_semester\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${change.change_semester }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"div변동구분\" class=\"form-control\" name=\"change_sub\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${change.change_sub }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"div변동학년\" class=\"form-control\" name=\"change_level\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${change.change_level }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"div변동일\" class=\"form-control\" name=\"change_date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${change.change_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
